# Configuration of the messaging system. For demo internal in-memory messaging is used
messaging:
  type_name: spade_llm.core.messaging.DictionaryMessageService
# Configuration of the agent state storage. For demo internal in-memory storage is used
storage:
  type_name: spade_llm.core.storage.InMemoryStorageFactory
# Agents to host in the system
agents:
  # Console agent which listens for commands from console and sends them to the delegate agent
  first:
    type_name: spade_llm.demo.platform.gaia2_benchmark.agents.FirstAgent
  platform_agent:
    type_name: spade_llm.demo.platform.gaia2_benchmark.agents.PlatformAgent
    args:
      model: max
      senat_agents: [ first ]
wait_for_agents: [ platform_agent ]
