# Configuration of the messaging system. For demo internal in-memory messaging is used
messaging:
  type_name: spade_llm.core.messaging.DictionaryMessageService
# Configuration of the agent state storage. For demo internal in-memory storage is used
storage:
  type_name: spade_llm.core.storage.InMemoryStorageFactory
# Active scenario for the auction (scenario_a, scenario_b, or scenario_c)
scenario: scenario_a
chat_models:
  max:
    type_name: spade_llm.models.gigachat.GigaChatModelFactory
    args:
      credentials: env.GIGA_CRED
      scope: env.GIGACHAT_SCOPE
      model: GigaChat-2-Max
      verify_ssl_certs: False
# Agents to host in the system
agents:

  proposal_board:
    type_name: spade_llm.demo.platform.auction.agents.ProposalBoardAgent
    args:
      total_rounds: 3
      stable_limit: 3
      max_price: 750
  first_merchant:
    type_name: spade_llm.demo.platform.auction.agents.FirstMerchantAgent
    args:
      model: max
      enable_trust_mechanism: true
  second_merchant:
    type_name: spade_llm.demo.platform.auction.agents.SecondMerchantAgent
    args:
      model: max
      enable_trust_mechanism: true
  third_merchant:
    type_name: spade_llm.demo.platform.auction.agents.ThirdMerchantAgent
    args:
      model: max
      enable_trust_mechanism: true
  fourth_merchant:
    type_name: spade_llm.demo.platform.auction.agents.FourthMerchantAgent
    args:
      model: max
      enable_trust_mechanism: true
  fifth_merchant:
    type_name: spade_llm.demo.platform.auction.agents.FifthMerchantAgent
    args:
      model: max
      enable_trust_mechanism: true
  # Console agent which listens for commands from console and sends them to the delegate agent
  console:
    type_name: spade_llm.agents.console.ConsoleAgent
    args:
      delegate_type: proposal_board
      prompt: Нажмите Enter
      timeout: 200
  df:
    type_name: spade_llm.demo.platform.contractnet.discovery.DirectoryFacilitatorAgent
# Agents to wait for before stopping the system. The system stops when all agents from this list are stopped.
wait_for_agents: [ console ]
